#!/usr/bin/python
# -*- coding: utf-8 -*-
import os, sys, re
from PySvnHooks import PySvnHook, PreCommitHook

def usage_and_exit( error_message = None ):
  """Print usage information and exit."""
  stream = ( error_message and sys.stderr ) or sys.stdout
  if error_message:
    stream.write( "ERROR: %s\n\n" % error_message )
  stream.write(
    "USAGE: %s REPOSITORY TRANSACTION_NAME\n"
    % ( os.path.basename( sys.argv[ 0 ] ) )
  )
  sys.exit( ( error_message and 1 ) or 0 )


if __name__ == '__main__':
    if len( sys.argv ) != 3:
        usage_and_exit( )
    else:
        sys.exit( PreCommitHook( repository=sys.argv[ 1 ], txn_name=sys.argv[ 2 ] ).run_tests() )
